version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wallet_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network

  app:
    build: .
    container_name: wallet_app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      HIKARI_MAX_POOL_SIZE: 50
      JPA_LOCK_TIMEOUT: 5000
    depends_on:
      - db
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge