spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      javax.persistence.lock.timeout: ${JPA_LOCK_TIMEOUT:5000}
    hibernate.ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.xml
    drop-first: false
